from flask import request, jsonify
import queries as db

def configurar_rutas(app):
    @app.route('/create_user', methods=['POST'])
    def create_user(): return jsonify(db.db_create_user(request.json))
    @app.route('/login', methods=['POST'])
    def login(): 
        data = request.json
        return jsonify(db.db_login(data.get('correo'), data.get('clave')))
    @app.route('/asistencias/<int:id_usuario>', methods=['GET'])
    def get_asistencias(id_usuario): return jsonify(db.db_get_asistencias(id_usuario))
    @app.route('/cursos/profesor/<int:id_usuario>', methods=['GET'])
    def get_cursos_profesor(id_usuario): return jsonify(db.db_get_cursos_profesor(id_usuario))
    @app.route('/modulos/curso/<int:id_curso>', methods=['GET'])
    def get_modulos_curso(id_curso): return jsonify(db.db_get_modulos_curso(id_curso))
    @app.route('/modulo/<int:id_modulo>/students', methods=['GET'])
    def get_estudiantes(id_modulo): return jsonify(db.db_get_estudiantes(id_modulo))
    @app.route('/asistencia/registrar', methods=['POST'])
    def registrar_asistencia(): return jsonify(db.db_registrar_asistencia(request.json))
    @app.route('/admin/asistencias', methods=['GET'])
    def get_admin_asistencias(): return jsonify(db.db_get_admin_asistencias())
    @app.route('/admin/notas', methods=['GET'])
    def get_admin_notas(): return jsonify(db.db_get_admin_notas())
    @app.route('/notas/modulo/<int:id_modulo>', methods=['GET'])
    def get_notas_modulo(id_modulo): return jsonify(db.db_get_notas_modulo(id_modulo))
    @app.route('/notas', methods=['POST'])
    def guardar_nota(): return jsonify(db.db_guardar_nota(request.json))
    @app.route('/notas/<int:id_nota>', methods=['DELETE'])
    def eliminar_nota(id_nota): return jsonify(db.db_eliminar_nota(id_nota))
    @app.route('/notas-alumno/<int:id_usuario>', methods=['GET'])
    def obtener_notas_estudiante(id_usuario): return jsonify(db.db_obtener_notas_estudiante(id_usuario))
    @app.route('/cursos', methods=['GET'])
    def get_cursos(): return jsonify(db.db_get_cursos())
    @app.route('/cursos/crear', methods=['POST'])
    def crear_curso(): return jsonify(db.db_crear_curso(request.json))
    @app.route('/cursos/editar/<int:id_curso>', methods=['PUT'])
    def editar_curso(id_curso): return jsonify(db.db_editar_curso(id_curso, request.json))
    @app.route('/cursos/eliminar/<int:id_curso>', methods=['DELETE'])
    def eliminar_curso(id_curso): return jsonify(db.db_eliminar_curso(id_curso))
    @app.route('/modulos', methods=['GET'])
    def get_modulos(): return jsonify(db.db_get_modulos())
    @app.route('/modulos/crear', methods=['POST'])
    def crear_modulo(): return jsonify(db.db_crear_modulo(request.json))
    @app.route('/modulos/editar/<int:id_modulo>', methods=['PUT'])
    def editar_modulo(id_modulo): return jsonify(db.db_editar_modulo(id_modulo, request.json))
    @app.route('/modulos/eliminar/<int:id_modulo>', methods=['DELETE'])
    def eliminar_modulo(id_modulo): return jsonify(db.db_eliminar_modulo(id_modulo))